name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  Registery: docker.io
  ImageName: alienkh/ardupilot_sim_ros2
  ImageTag: ${{ github.run_number }}

jobs:

  build_and_push_docker_image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      
    steps:
      - name: setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.Registery }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push docker image for not using GPU
        id: build-and-push-NoGPU
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.Registery }}/${{ env.ImageName }}:${{ env.ImageTag }}
          file: ./Dockerfile_ardupilot_sim_NO_GPU


          
  # build_and_push_docker_image_GPU_Enabled:

  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #     id-token: write

  #   steps:
  #     - name: setup Docker buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Login to DockerHub
  #       if: github.event_name != 'pull_request'
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ${{ env.Registery }}
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
      
      # - name: Build and Push docker image for using Nvidia GPU
      #   id: build-and-push
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags:   ${{ env.Registery }}/${{ env.ImageName }}:${{ env.ImageTag }}_GPU
      #     file: ./dockerFile/Dockerfile_ardupilot_sim_with_GPU

